### ISSUE TITLE
[Admin] Define function test of login page

### ISSUE THREAD

**Issue by smileLoopy** [smileLoopy/personal-project-forum-admin#17]
Review whether testing is necessary to implement the login function and prepare for the admin user function and Kakao OAuth authentication.

## TODO

- [ ] Check login settings and test
- [ ] Check admin user function
- [x] Prepare Kakao OAuth authentication and check test
