### ISSUE TITLE
[Admin] Implement authentication

### ISSUE THREAD

**Issue by smileLoopy** [smileLoopy/personal-project-forum-admin#24]
Implement admin authentication function.

## TODO

- [x] Implementing back end authentication: DB authentication
- [x] Kakao authentication (OAuth 2.0)
    - [ ] Fixed a bug in the logic that saves and synchronizes user information to DB at the time of initial Kakao authentication
- [x] Kakao developer setting tasks
    - [x] Register application for admin
    - [x] Check Rest API
    - [x] Register website domain
    - [x] Register redirect URL
    - [x] Setting agree items
    - [x] Check Client Secret key

**Comment by smileLoopy** [comment]
While trying Kakao authentication, found a bug. Fix it from this issue
