### ISSUE TITLE
[Admin] Define database access logic test

### ISSUE THREAD

**Issue by smileLoopy** [smileLoopy/personal-project-forum-admin#6]
Setting the environment and define tests so that the admin project can use the database.

## TODO

- [x] Create db
- [x] Give account priviliege
- [x] Design IDE access environment
- [ ] Write repository codes
- [ ] Write related tests
