### ISSUE TITLE
[Admin] Define view end point test

### ISSUE THREAD

**Issue by smileLoopy** [smileLoopy/personal-project-forum-admin#8]
Define the views and specifications to be provided to the admin service in advance through testing. 

Detailed specifications that will be included while implementing the function will be dealt with as a separate issue later.

## TODO

- [x] Main root view
- [ ] Posting related view
- [x] Comment related view
- [ ] User related view
- [x] Admin user related view
