### ISSUE TITLE
[Admin] Check out AdminLTE - basic setup

### ISSUE THREAD

**Issue by smileLoopy** [smileLoopy/personal-project-forum-admin#9]
In order to easily configure the admin service UI, review whether to use AdminLTE and set up the basic configuration so that it can be used in a Spring Boot project.

## TODO
- [x] Research about AdminLTE
- [x] Apply AdminLTE to html markup
- [x] Organizing template layers

## Reference
AdminLTE 공식 홈페이지: https://adminlte.io/
AdminLTE 라이브 데모: https://adminlte.io/themes/v3/
AdminLTE Github: https://github.com/ColorlibHQ/AdminLTE

**Comment by smileLoopy** [comment]
I pushed to the main branch...!! mistake
